namespace OETicket.Application.Features.CardApplications.DTOs;

public sealed record CardApplicationDto(
    long Id,
    DateOnly ApplicationDate,
    char ApplicationType,
    string ApplicationBatchCode,
    string? Title,
    string GivenName,
    string? FamilyName,
    string? MiddleName,
    char Gender,
    int Age,
    DateOnly? DateOfBirth,
    string MobileNumber,
    string? Email,
    string BloodGroup,
    string? MedicalProblem,
    char IsDiabetes,
    char IsHypertension,
    char IsCAD,
    char ApplicationStatus,
    bool IsCardGenerated,
    string ApplicationCentreId,
    string CreatedBy,
    DateTime CreatedOn
);

public sealed record CreateCardApplicationDto(
    DateOnly ApplicationDate,
    char ApplicationType,
    string ApplicationBatchCode,
    string? Title,
    string GivenName,
    string? FamilyName,
    string? MiddleName,
    string? CareOfName,
    char Gender,
    int Age,
    DateOnly? DateOfBirth,
    string AddressId,
    string MobileNumber,
    string? EmergencyNumber,
    string? Email,
    string WeeklySatsangCentreId,
    string? MedicalProblem,
    char IsDiabetes,
    char IsHypertension,
    char IsCAD,
    string BloodGroup,
    char? IsAttendantAllowed,
    string? AttendantName,
    string? DrugAllergies,
    string? Remark,
    char IsOldCardAttached,
    string ApplicationCentreId,
    string? Uid
);
