using MediatR;
using OETicket.Application.Common.Interfaces;
using OETicket.Application.Common.Models;
using OETicket.Application.Features.CardApplications.DTOs;
using OETicket.Domain.Entities;

namespace OETicket.Application.Features.CardApplications.Commands;

// ── Response DTO ────────────────────────────────────────────────────────────
public sealed record NewTokenResponseDto(
    long ApplicationId,
    string TokenNumber,
    string FullName,
    char Gender,
    int Age,
    string MobileNumber,
    DateOnly ApplicationDate
);

// ── Command ─────────────────────────────────────────────────────────────────
public sealed record CreateNewTokenCommand(NewTokenRequestDto Dto)
    : IRequest<ApiResponse<NewTokenResponseDto>>;

// ── Handler ─────────────────────────────────────────────────────────────────
public sealed class CreateNewTokenCommandHandler(
    IApplicationDbContext dbContext,
    ICurrentUserService currentUserService)
    : IRequestHandler<CreateNewTokenCommand, ApiResponse<NewTokenResponseDto>>
{
    public async Task<ApiResponse<NewTokenResponseDto>> Handle(
        CreateNewTokenCommand request,
        CancellationToken cancellationToken)
    {
        var dto   = request.Dto;
        var now   = DateTime.UtcNow;
        var user  = currentUserService.UserName ?? "system";
        var today = DateOnly.FromDateTime(now);

        // Map "Male" / "Female" / "Other" → 'M' / 'F' / 'O'
        var gender = dto.Gender?.Trim().ToUpperInvariant() switch
        {
            "MALE"   => 'M',
            "FEMALE" => 'F',
            _        => 'O'
        };

        // Parse ISO date string → DateOnly
        DateOnly? dob = DateOnly.TryParse(dto.DateOfBirth, out var parsedDob) ? parsedDob : null;

        // Generate a daily batch code  e.g. "BATCH20260525"
        var batchCode = $"B{today:yyyyMMdd}";

        var application = new CardApplication
        {
            // Id is auto-generated by the sequence
            ApplicationDate      = today,
            ApplicationType      = 'N',          // N = New application
            ApplicationBatchCode = batchCode.PadRight(15).Substring(0, 15),
            GivenName            = dto.FirstName.Trim(),
            FamilyName           = dto.LastName?.Trim(),
            MiddleName           = dto.MiddleName?.Trim(),
            Gender               = gender,
            Age                  = dto.Age,
            DateOfBirth          = dob,
            MobileNumber         = dto.MobileNumber.Trim(),
            Uid                  = dto.AadhaarNumber?.Trim(),

            // Sensible defaults for legacy required fields
            AddressId            = "DEFAULT",
            WeeklySatsangCentreId = "DEFAULT",
            ApplicationCentreId  = "DEFAULT",
            IsDiabetes           = 'N',
            IsHypertension       = 'N',
            IsCAD                = 'N',
            BloodGroup           = "O+  ",       // padded to char(4)
            IsOldCardAttached    = 'N',

            ApplicationStatus    = 'P',          // Pending
            IsCardGenerated      = false,
            RecordStatus         = 'A',
            CreatedBy            = user[..Math.Min(user.Length, 25)],
            CreatedOn            = now,
            UpdatedBy            = user[..Math.Min(user.Length, 25)],
            UpdatedOn            = now
        };

        dbContext.CardApplications.Add(application);
        await dbContext.SaveChangesAsync(cancellationToken);

        // Token number format: TC.DD MM YYYY <ID padded to 6>
        var tokenNumber = $"TC.{today:dd MM yyyy} {application.Id:D6}";
        var fullName    = string.Join(" ",
            new[] { dto.FirstName, dto.MiddleName, dto.LastName }
                .Where(s => !string.IsNullOrWhiteSpace(s)));

        return ApiResponse<NewTokenResponseDto>.Ok(
            new NewTokenResponseDto(
                application.Id,
                tokenNumber,
                fullName,
                gender,
                dto.Age,
                dto.MobileNumber,
                today),
            "Token created successfully.");
    }
}
